version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8320:5000"
    expose:
      - "8320"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=mysql+pymysql://user:password@db/habits_db
    depends_on:
      - db
    # TODO: Add a proper wait-for script.
    command: >
      sh -c "
        sleep 2;
        flask db upgrade && flask run --host=0.0.0.0"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: habits_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  frontend:
    build:
      context: ./frontend-web
      args:
        - VITE_API_URL=http://localhost:8320
    ports:
      - "8321:80"
    depends_on:
      - backend
volumes:
  db_data: